from . import res_partner
from . import jewelry_ticket
from . import jewelry_ticket_line
from . import product_promotion
from . import associate_account
from . import associate_transaction
from . import purchase_order
from . import purchase_order_line
from . import supplier_account
from . import casse_melting
from . import casse_melting_line
from . import service_order
from . import atelier_price_table
from . import daily_cash_register
from . import cash_register_line
from . import gold_movement
from . import cash_movement_category
