{
    'name': 'Jewelry Transactions',
    'version': '17.0.1.0.0',
    'category': 'Sales',
    'summary': 'Cœur métier — tickets, achats, services, caisse, fonte casse',
    'depends': ['jewelry_core', 'account', 'purchase'],
    'data': [
        'security/ir.model.access.csv',
        'data/atelier_price_data.xml',
        'data/sequence_data.xml',
        'views/actions.xml',
        'views/ticket_views.xml',
        'views/promotion_views.xml',
        'views/purchase_views.xml',
        'views/supplier_account_views.xml',
        'views/casse_melting_views.xml',
        'views/service_views.xml',
        'views/cash_register_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'license': 'LGPL-3',
    'post_init_hook': 'apply_translations',
    'demo': [
        'demo/demo_data.xml',
    ],
}
