{
    'name': 'Jewelry Transactions',
    'version': '17.0.2.0.0',
    'category': 'Sales',
    'summary': 'Cœur métier — tickets, achats, services, caisse, fonte casse',
    'depends': ['mail', 'jewelry_core', 'account', 'purchase'],
    'data': [
        'security/ir.model.access.csv',
        'data/atelier_price_data.xml',
        'data/sequence_data.xml',
        'views/wizard_views.xml',
        'views/cash_movement_views.xml',
        'views/actions.xml',
        'views/ticket_views.xml',
        'views/partner_views.xml',
        'views/promotion_views.xml',
        'views/purchase_views.xml',
        'views/supplier_account_views.xml',
        'views/associate_views.xml',
        'views/casse_melting_views.xml',
        'views/service_views.xml',
        'views/cash_register_views.xml',
        'views/cash_movement_category_views.xml',
        'views/cash_safe_views.xml',
        'views/menus.xml',
        'data/cash_movement_category_data.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'jewelry_transactions/static/src/scss/ticket_list_view.scss',
            'jewelry_transactions/static/src/scss/ticket_form_view.scss',
            'jewelry_transactions/static/src/js/product_statusbar.js',
            'jewelry_transactions/static/src/js/cash_register_live.js',
        ],
    },
    'installable': True,
    'license': 'LGPL-3',
    'post_init_hook': 'apply_translations',
    'demo': [
        'demo/demo_data.xml',
    ],
}
